name: material_pagination
description: "MaterialPagination is a versatile Flutter widget for pagination, offering customizable page buttons and navigation arrows, perfect for enhancing user navigation."
version: 1.0.1
homepage:  https://github.com/shyamexe/material_pagination?tab=readme-ov-file#readme
repository: https://github.com/shyamexe/material_pagination 
topics: [material, pagination,page]
documentation: https://pub.dev/documentation/material_pagination/latest/

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
# flutter:
#   plugin:
#     platforms:
#       android: 
#         pluginClass: MaterialPaginationPlugin
#       ios:
#         pluginClass: MaterialPaginationPlugin
#       web:
#         pluginClass: MaterialPaginationWeb
#         fileName: material_pagination_web.dart
#       linux:
#         pluginClass: MaterialPaginationPlugin
#       macos:
#         pluginClass: MaterialPaginationPlugin
#       windows:
#         pluginClass: MaterialPaginationPlugin
screenshots:
  - description: screenshots.
    path: screenshots/image.png